create table if not exists classes (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default now()
);

create table if not exists subjects (
    id bigint generated by default as identity primary key,
    name text not null,
    class_id bigint references classes(id) on delete cascade,
    weekly_periods int not null default 1,
    created_at timestamp with time zone default now()
);

create table if not exists teachers (
    id bigint generated by default as identity primary key,
    name text not null,
    subjects text default '',
    created_at timestamp with time zone default now()
);

create table if not exists rooms (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default now()
);

create table if not exists timetables (
    id bigint generated by default as identity primary key,
    class_id bigint,
    class_name text,
    subject_id bigint,
    subject_name text,
    teacher_id bigint,
    teacher_name text,
    room_id bigint,
    room_name text,
    day text,
    time_slot text,
    created_at timestamp with time zone default now()
);

alter table classes enable row level security;
alter table subjects enable row level security;
alter table teachers enable row level security;
alter table rooms enable row level security;
alter table timetables enable row level security;

create policy "Allow public read classes" on classes for select using (true);
create policy "Allow public insert classes" on classes for insert with check (true);
create policy "Allow public delete classes" on classes for delete using (true);

create policy "Allow public read subjects" on subjects for select using (true);
create policy "Allow public insert subjects" on subjects for insert with check (true);
create policy "Allow public delete subjects" on subjects for delete using (true);

create policy "Allow public read teachers" on teachers for select using (true);
create policy "Allow public insert teachers" on teachers for insert with check (true);
create policy "Allow public delete teachers" on teachers for delete using (true);

create policy "Allow public read rooms" on rooms for select using (true);
create policy "Allow public insert rooms" on rooms for insert with check (true);
create policy "Allow public delete rooms" on rooms for delete using (true);

create policy "Allow public read timetables" on timetables for select using (true);
create policy "Allow public insert timetables" on timetables for insert with check (true);
create policy "Allow public delete timetables" on timetables for delete using (true);
